### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by jakub-prokop** [HReynaud/EchoNet-Synthetic#1]
Hi! Thank you for sharing this interesting work. 

I am unable to access pretrained models through the links you provided. Is this an issue on my side, or are they misconfigured?

Thanks in advance!

**Comment by HReynaud** [comment]
Hello, thanks for your interest in this work.

All the models are not fully ready to be published yet, but you can download the ones used in the HuggingFace demo: https://huggingface.co/spaces/HReynaud/EchoNet-Synthetic/tree/main/resources

This should give you a good starting point to test the pipeline locally, without the privacy step, and only for the Dynamic data (adult, A4C)

I hope this helps !

**Comment by jakub-prokop** [comment]
Thanks!
