### ISSUE TITLE
Pretrained models with unet

### ISSUE THREAD

**Issue by giovanlee** [HReynaud/EchoNet-Synthetic#2]
Hi! Thanks for interesting work.

I have pretrained models from https://github.com/HReynaud/EchoNet-Synthetic/issues/1#issuecomment-2262554557 , 
however when I sample image from LIDM, with code 
`# For the Dynamic dataset
python echosyn/lidm/sample.py \
    --config echosyn/lidm/configs/dynamic.yaml \
    --unet experiments/lidm_dynamic/checkpoint-500000/unet_ema \
    --vae models/vae \
    --output samples/lidm_dynamic \
    --num_samples 50000 \
    --batch_size 128 \
    --num_steps 64 \
    --save_latent \
    --seed 0`
I need --unet ckpts, but where can I get this lidm_dynamic/checkpoint ?

Thank you.

**Comment by HReynaud** [comment]
Hello, thanks for our interest in this work !

I believe you should be able to run the code with this checkpoint and json file, simply put both files in a folder and replace the path `experiments/lidm_dynamic/checkpoint-500000/unet_ema` with your folder path.
 https://huggingface.co/spaces/HReynaud/EchoNet-Synthetic/tree/main/resources/lidm

You can also check the demo code on huggingface: 
https://huggingface.co/spaces/HReynaud/EchoNet-Synthetic/blob/main/app.py
It has the whole LIDM + LVDM + VAE pipeline implemented.

**Comment by giovanlee** [comment]
Thank you for reply!  I'll try code with your comment!
